version: "3.3"
services:
  container0:
    container_name: fog0
    build:
      context: ./FogNode
      dockerfile: Dockerfile
      #args:
       # buildno: 1
    image: alefanfi/ubuntu20.04:latest
    #command: python fog.py
    volumes:
      - ./FogNode:/fog
    ports:
      - "8080:8080"

  container1:
    container_name: fog1
    build:
      context: ./FogNode
      dockerfile: Dockerfile
      #args:
      # buildno: 1
    image: alefanfi/ubuntu20.04:latest
    #command: python fog.py
    volumes:
      - ./FogNode:/fog
    ports:
      - "8081:8080"


  container2:
    container_name: fog2
    build:
      context: ./FogNode
      dockerfile: Dockerfile
      #args:
      # buildno: 1
    image: alefanfi/ubuntu20.04:latest
    #command: python fog.py
    volumes:
      - ./FogNode:/fog
    ports:
      - "8082:8080"