version: '3.3'

services:
    reverseproxy:
        build:
            context: ./ReverseProxy
            dockerfile: Dockerfile
        image: nginx:alpine
        ports:
            - "5000:5000"
        restart: always
        depends_on:
            -   fognode
        networks:
            - proxynet

    fognode:
        build:
            context: ./FogNode
            dockerfile: Dockerfile
            #args:
             # buildno: 1
        image: alefanfi/ubuntu20.04:latest
        #command: python fog.py
        volumes:
            - ./ReverseProxy:/fog
        expose:
            - "8080"
            - "8081"
        networks:
            - proxynet

networks:
    proxynet:
        name: custom_network